version: "3.4"
services:
  api:
    build:
      context: .
      target: release
    entrypoint: "/app/start.dev.sh"
    command: "--reload"
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql://turbo:passpass@db:5432/apidb
    networks:
      - default
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - ./src:/app

  db:
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=turbo
      - POSTGRES_PASSWORD=passpass
      - POSTGRES_DB=apidb
    image: postgres:11.1-alpine
    networks:
      - default
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - .db:/var/lib/postgresql/data
